version: '2'
services:
  myztl5-app:
    image: myztl5
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myztl5-postgresql:5432/myztl5
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8088:8088
  myztl5-postgresql:
    extends:
      file: postgresql.yml
      service: myztl5-postgresql
